"""
One-time script: extracts POWERS, COEF, and INTERCEPT tables from
filament_mixer_model.h and writes them as a compact Python literal file.

Run once from the project root:
    python tools/extract_filament_mixer.py

Outputs: io_mesh_3mf/common/_filament_mixer_data.py
"""
import re
import os

SRC = os.path.join(
    os.path.dirname(__file__),
    "..", "ReferenceFiles", "OrcaSlicer-FullSpectrum-main",
    "src", "libslic3r", "filament_mixer_model.h"
)
OUT = os.path.join(
    os.path.dirname(__file__),
    "..", "io_mesh_3mf", "common", "_filament_mixer_data.py"
)


def parse_nested_int_array(text, name):
    """Extract a 2-D int array like `int NAME[M][N] = {{...}, {...}};`."""
    # Find the array declaration
    pattern = rf"static\s+const\s+int\s+{name}\[(\d+)\]\[(\d+)\]\s*=\s*\{{"
    m = re.search(pattern, text)
    if not m:
        raise ValueError(f"Could not find array {name}")
    rows, cols = int(m.group(1)), int(m.group(2))
    start = m.end()

    # Extract everything up to the matching closing brace of the outer array
    depth = 1
    end = start
    while end < len(text) and depth > 0:
        c = text[end]
        if c == '{':
            depth += 1
        elif c == '}':
            depth -= 1
        end += 1

    block = text[start:end - 1]
    # Remove inner braces and parse numbers
    block = block.replace('{', '').replace('}', '')
    numbers = [int(x.strip()) for x in re.split(r'[,\s]+', block) if x.strip()]
    assert len(numbers) == rows * cols, f"{name}: expected {rows*cols}, got {len(numbers)}"
    return [numbers[i * cols:(i + 1) * cols] for i in range(rows)]


def parse_nested_double_array(text, name):
    """Extract a 2-D double array like `double NAME[M][N] = {{...}, {...}};`."""
    pattern = rf"static\s+const\s+double\s+{name}\[(\d+)\]\[(\d+)\]\s*=\s*\{{"
    m = re.search(pattern, text)
    if not m:
        raise ValueError(f"Could not find array {name}")
    rows, cols = int(m.group(1)), int(m.group(2))
    start = m.end()

    depth = 1
    end = start
    while end < len(text) and depth > 0:
        c = text[end]
        if c == '{':
            depth += 1
        elif c == '}':
            depth -= 1
        end += 1

    block = text[start:end - 1]
    block = block.replace('{', '').replace('}', '')
    # Match numbers including scientific notation
    numbers = [float(x) for x in re.findall(r'[-+]?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?', block)]
    assert len(numbers) == rows * cols, f"{name}: expected {rows*cols}, got {len(numbers)}"
    return [numbers[i * cols:(i + 1) * cols] for i in range(rows)]


def parse_double_array(text, name):
    """Extract a 1-D double array like `double NAME[N] = {...};`."""
    pattern = rf"static\s+const\s+double\s+{name}\[(\d+)\]\s*=\s*\{{"
    m = re.search(pattern, text)
    if not m:
        raise ValueError(f"Could not find array {name}")
    n = int(m.group(1))
    start = m.end()
    depth = 1
    end = start
    while end < len(text) and depth > 0:
        c = text[end]
        if c == '{':
            depth += 1
        elif c == '}':
            depth -= 1
        end += 1
    block = text[start:end - 1]
    numbers = [float(x) for x in re.findall(r'[-+]?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?', block)]
    assert len(numbers) == n, f"{name}: expected {n}, got {len(numbers)}"
    return numbers


def main():
    print(f"Reading: {SRC}")
    with open(SRC, "r", encoding="utf-8") as f:
        text = f.read()

    print("Parsing POWERS...")
    powers = parse_nested_int_array(text, "POWERS")
    print(f"  {len(powers)} rows x {len(powers[0])} cols")

    print("Parsing COEF...")
    coef = parse_nested_double_array(text, "COEF")
    print(f"  {len(coef)} rows x {len(coef[0])} cols")

    print("Parsing INTERCEPT...")
    intercept = parse_double_array(text, "INTERCEPT")
    print(f"  {len(intercept)} values")

    # Write output
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write('# Auto-generated by tools/extract_filament_mixer.py\n')
        f.write('# Data extracted from OrcaSlicer-FullSpectrum filament_mixer_model.h\n')
        f.write('# Original model: MIT License, Copyright 2026 Justin Hayes\n')
        f.write('# Degree-4 polynomial regression approximating Mixbox pigment mixing.\n')
        f.write('# Mean Delta-E ~2.07 vs Mixbox reference.\n')
        f.write('#\n')
        f.write('# POWERS[330][7] - monomial exponents for 7 inputs (r1,g1,b1,r2,g2,b2,t)\n')
        f.write('# COEF[330][3]   - regression coefficients for 3 outputs (r,g,b)\n')
        f.write('# INTERCEPT[3]   - bias terms for 3 outputs (r,g,b)\n')
        f.write('\n')
        f.write(f'POWERS = {repr(powers)}\n')
        f.write('\n')
        f.write(f'COEF = {repr(coef)}\n')
        f.write('\n')
        f.write(f'INTERCEPT = {repr(intercept)}\n')

    print(f"Written: {OUT}")


if __name__ == "__main__":
    main()
